spring:
  data:
    mongodb:
      port: 27017
      username: "user"
      password: "pass"
      host: "localhost"
      database: "weather"
      authentication-database: "admin"
server:
  port: 8080
