server:
  port: ${SERVER_PORT:8080}
  address: ${SERVER_ADDRESS:localhost}
  tomcat:
    remoteip:
      protocol-header-https-value: http
spring:
  application:
    name: openweather
  data:
    mongodb:
      port: 27017
      username: user
      password: pass
      host: ${MONGO:localhost}
      database: weather
      authentication-database: admin
weather:
  open-weather-api-url: https://api.openweathermap.org/data/3.0/onecall
  gateway:
    port: ${APIGATEWAY_SERVER_PORT}
    address: ${APIGATEWAY_SERVER_ADDRESS}
    schema: ${server.tomcat.remoteip.protocol-header-https-value}