server:
  port: ${SERVER_PORT:8080}
  address: ${SERVER_ADDRESS:localhost}
weather:
  open-weather-api-url: "https://api.openweathermap.org/data/3.0/onecall"
  weather-plan-open-url: "http://${server.address}:${server.port}/open/current"
spring:
  application:
    name: "openweather"
  data:
    mongodb:
      port: 27017
      username: "user"
      password: "pass"
      host: ${MONGO:localhost}
      database: "weather"
      authentication-database: "admin"