server:
  port: 8080
weather:
  open-weather-api-url: "https://api.openweathermap.org/data/3.0/onecall"
  weather-plan-open-url: "http://localhost:8083/open/current"
spring:
  application:
    name: "openweather"
  data:
    mongodb:
      port: 27017
      username: "user"
      password: "pass"
      host: ${MONGO:localhost}
      database: "weather"
      authentication-database: "admin"