server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}
  tomcat:
    remoteip:
      protocol-header-https-value: http
spring:
  application:
    name: homeweather
  data:
    mongodb:
      port: 27017
      username: user
      password: pass
      host: ${MONGO}
      database: weather
      authentication-database: admin
weather:
  open-weather-api-url: https://api.openweathermap.org/data/3.0/onecall
  weather-plan-open-url: ${OPEN_WEATHER_URL}