server:
  port: ${SERVER_PORT:8081}
  address: ${SERVER_ADDRESS:localhost}
spring:
  data:
    mongodb:
      port: 27017
      username: "user"
      password: "pass"
      host: ${MONGO:localhost}
      database: "weather"
      authentication-database: "admin"
  application:
    name: "homeweather"
weather:
  open-weather-api-url: "https://api.openweathermap.org/data/3.0/onecall"
  weather-plan-open-url: ${OPEN_WEATHER_URL:http://localhost:8083/open/current}