version: '3.8'
services:
  mongodb:
    container_name: mongo-db
    image: mongodb/mongodb-community-server:6.0.4-ubi8
    restart: always
    env_file:
      - .env.db.dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - weather-network
    ports:
      - "27017:27017"