version: '3.8'
networks:
  weather-network:
    name: weather-network
    driver: bridge
services:
  mongo-db:
    container_name: mongo-db-service
    image: mongodb/mongodb-community-server:6.0.4-ubi8
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - weather-network
    ports:
      - ${MONGODB_SERVER_PORT}:27017
  homeweather:
    container_name: homeweather-service
    image: homeweather:1.0-SNAPSHOT
    env_file:
      - .env
    environment:
      #     server
      - SERVER_PORT=${HOMEWEATHER_SERVER_PORT}
      - SERVER_ADDRESS=${HOMEWEATHER_SERVER_ADDRESS}
      #     apigateway
      - APIGATEWAY_SERVER_PORT=${APIGATEWAY_SERVER_PORT}
      - APIGATEWAY_SERVER_ADDRESS=${APIGATEWAY_SERVER_ADDRESS}
      #     db
      - DB_NAME=${DB_NAME}
      - MONGO=mongo-db
      #     routes
      - OPEN_WEATHER_URL=http://${OPENWEATHER_SERVER_ADDRESS}:${OPENWEATHER_SERVER_PORT}/api/open/current
    networks:
      - weather-network
    ports:
      - ${HOMEWEATHER_SERVER_PORT}:${HOMEWEATHER_SERVER_PORT}
    depends_on:
      - mongo-db
      - openweather
      - apigateway
  openweather:
    container_name: openweather-service
    image: openweather:1.0-SNAPSHOT
    env_file:
      - .env
    environment:
      #     server
      - SERVER_PORT=${OPENWEATHER_SERVER_PORT}
      - SERVER_ADDRESS=${OPENWEATHER_SERVER_ADDRESS}
      #     apigateway
      - APIGATEWAY_SERVER_PORT=${APIGATEWAY_SERVER_PORT}
      - APIGATEWAY_SERVER_ADDRESS=${APIGATEWAY_SERVER_ADDRESS}
      #     db
      - DB_NAME=${DB_NAME}
      - MONGO=mongo-db
      #     openweathermap
      - appid=${OPENWEATHERMAP_APPID}
    networks:
      - weather-network
    ports:
      - ${OPENWEATHER_SERVER_PORT}:${OPENWEATHER_SERVER_PORT}
    depends_on:
      - mongo-db
      - apigateway
  smssender:
    container_name: smssender-service
    image: smssender:1.0-SNAPSHOT
    env_file:
      - .env
    environment:
      #     server
      - SERVER_PORT=${SMSSENDER_SERVER_PORT}
      - SERVER_ADDRESS=${SMSSENDER_SERVER_ADDRESS}
      #     apigateway
      - APIGATEWAY_SERVER_PORT=${APIGATEWAY_SERVER_PORT}
      - APIGATEWAY_SERVER_ADDRESS=${APIGATEWAY_SERVER_ADDRESS}
      #     db
      - DB_NAME=${DB_NAME}
      - MONGO=mongo-db
      #     twilio
      - ACCOUNT_SID=${ACCOUNT_SID}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - TRIAL_NUMBER=${TRIAL_NUMBER}
      #     openweathermap
      - appid=${OPENWEATHERMAP_APPID}
    networks:
      - weather-network
    ports:
      - ${SMSSENDER_SERVER_PORT}:${SMSSENDER_SERVER_PORT}
    depends_on:
      - mongo-db
      - openweather
      - apigateway
  apigateway:
    container_name: apigateway-service
    image: apigateway:1.0-SNAPSHOT
    env_file:
      - .env
    environment:
      #      server
      - SERVER_PORT=${APIGATEWAY_SERVER_PORT}
      - SERVER_ADDRESS=${APIGATEWAY_SERVER_ADDRESS}
      #      routes
      - SMSSENDER_ROUTE_URI=http://${SMSSENDER_SERVER_ADDRESS}:${SMSSENDER_SERVER_PORT}
      - OPENWEATHER_ROUTE_URI=http://${OPENWEATHER_SERVER_ADDRESS}:${OPENWEATHER_SERVER_PORT}
      - HOMEWEATHER_ROUTE_URI=http://${HOMEWEATHER_SERVER_ADDRESS}:${HOMEWEATHER_SERVER_PORT}
    networks:
      - weather-network
    ports:
      - ${APIGATEWAY_SERVER_PORT}:${APIGATEWAY_SERVER_PORT}