server:
  port: ${SERVER_PORT:8081}
  address: ${SERVER_ADDRESS:localhost}
spring:
  data:
    mongodb:
      port: 27017
      username: "user"
      password: "pass"
      host: ${MONGO:localhost}
      database: "weather"
      authentication-database: "admin"
  application:
    name: "smssender"
twilio:
  twilio:
    accountSid: ${ACCOUNT_SID}
    authToken: ${AUTH_TOKEN}
    trialNumber: ${TRIAL_NUMBER}
messenger:
  schema: "http"
  sub-domain: "localhost"
