version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0.4-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"