version: '3.8'
networks:
  weather-network:
    name: weather-network
    driver: bridge
services:
  homeweather:
    container_name: homeweather-service
    image: homeweather:1.0-SNAPSHOT
    env_file:
      - .env.db.test
      - .env
    environment:
      - SERVER_PORT=${HOMEWEATHER_SERVER_PORT}
      - SERVER_ADDRESS=${HOMEWEATHER_SERVER_ADDRESS}
      - APIGATEWAY_SERVER_PORT=${APIGATEWAY_SERVER_PORT}
      - APIGATEWAY_SERVER_ADDRESS=${APIGATEWAY_SERVER_ADDRESS}
      - DB_NAME=${DB_NAME}
      - MONGO=${MONGO_SERVICE}
      - OPEN_WEATHER_URL=http://${OPENWEATHER_SERVER_ADDRESS}:${OPENWEATHER_SERVER_PORT}/api/open/current
    networks:
      - weather-network
    ports:
      - ${HOMEWEATHER_SERVER_PORT}:${HOMEWEATHER_SERVER_PORT}
    depends_on:
      - ${MONGO_SERVICE}
      - openweather
      - apigateway
  openweather:
    container_name: openweather-service
    image: openweather:1.0-SNAPSHOT
    env_file:
      - .env.db.test
      - .env
    environment:
      - SERVER_PORT=${OPENWEATHER_SERVER_PORT}
      - SERVER_ADDRESS=${OPENWEATHER_SERVER_ADDRESS}
      - APIGATEWAY_SERVER_PORT=${APIGATEWAY_SERVER_PORT}
      - APIGATEWAY_SERVER_ADDRESS=${APIGATEWAY_SERVER_ADDRESS}
      - DB_NAME=${DB_NAME}
      - MONGO=${MONGO_SERVICE}
      - appid=${APPID}
    networks:
      - weather-network
    ports:
      - ${OPENWEATHER_SERVER_PORT}:${OPENWEATHER_SERVER_PORT}
    depends_on:
      - ${MONGO_SERVICE}
      - apigateway
  smssender:
    container_name: smssender-service
    image: smssender:1.0-SNAPSHOT
    env_file:
      - .env.db.test
      - .env
    environment:
      - SERVER_PORT=${SMSSENDER_SERVER_PORT}
      - SERVER_ADDRESS=${SMSSENDER_SERVER_ADDRESS}
      - APIGATEWAY_SERVER_PORT=${APIGATEWAY_SERVER_PORT}
      - APIGATEWAY_SERVER_ADDRESS=${APIGATEWAY_SERVER_ADDRESS}
      - DB_NAME=${DB_NAME}
      - MONGO=${MONGO_SERVICE}
      - ACCOUNT_SID=${ACCOUNT_SID}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - TRIAL_NUMBER=${TRIAL_NUMBER}
      - appid=${APPID}
    networks:
      - weather-network
    ports:
      - ${SMSSENDER_SERVER_PORT}:${SMSSENDER_SERVER_PORT}
    depends_on:
      - ${MONGO_SERVICE}
      - openweather
      - apigateway
  apigateway:
    container_name: apigateway-service
    image: apigateway:1.0-SNAPSHOT
    env_file:
      - .env.db.test
      - .env
    environment:
#      server
      - SERVER_PORT=${APIGATEWAY_SERVER_PORT}
      - SERVER_ADDRESS=${APIGATEWAY_SERVER_ADDRESS}
#      routes
      - SMSSENDER_ROUTE_URI=http://${SMSSENDER_SERVER_ADDRESS}:${SMSSENDER_SERVER_PORT}
      - OPENWEATHER_ROUTE_URI=http://${OPENWEATHER_SERVER_ADDRESS}:${OPENWEATHER_SERVER_PORT}
      - HOMEWEATHER_ROUTE_URI=http://${HOMEWEATHER_SERVER_ADDRESS}:${HOMEWEATHER_SERVER_PORT}
    networks:
      - weather-network
    ports:
      - ${APIGATEWAY_SERVER_PORT}:${APIGATEWAY_SERVER_PORT}